version: "3"

# start with: docker-compose up &
# stop and remove containers with: docker-compose rm -s -f -v
services:
  db:
    image: mongo:3.6.18
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  backend:
    image: node:12.16.1-alpine
    ports:
      - "8888:8888"
    volumes:
      - ./backend/:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: sh -c "npm install && npm start"
    depends_on:
      - db

  frontend:
    image: node:12.16.1-alpine
    ports:
      - "5000:5000"
    volumes:
      - ./frontend/:/usr/src/app
    entrypoint: sh /usr/src/app/docker/entrypoint.sh
    depends_on:
      - backend

volumes:
  mongodbdata:
    external: false
